"""Creates a minimal test PDF with SIP spec content for CI testing."""
from fpdf import FPDF
from pathlib import Path


def create_test_spec():
    """Generate a tiny PDF with real SIP spec content for testing."""
    specs_dir = Path("data/specs")
    specs_dir.mkdir(parents=True, exist_ok=True)

    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", size=10)

    content = """RFC 3261 - SIP: Session Initiation Protocol (Test Excerpt)

Section 21.4.16 - 408 Request Timeout

The server could not produce a response within a suitable amount of time.
The client MAY repeat the request without modifications at any later time.

A 408 Response is generated by a UAS or proxy when a request cannot be
completed within the time indicated in the Expires header field. A UAC
that receives a 408 can consider the INVITE transaction as having failed.

Section 21.4.7 - 486 Busy Here

The callee's end system was contacted successfully, but the callee is
currently not willing or able to take additional calls at this end system.
The response MAY indicate a better time to call in the Retry-After header.

Section 21.4.2 - 481 Call/Transaction Does Not Exist

This indicates that the UAS received a request that does not match any
existing dialog or transaction. A 481 response to a BYE means the
call leg does not exist. A 481 response to a re-INVITE means the
dialog has been terminated.

Section 13.1 - INVITE Request

The INVITE method is used to establish a media session between user agents.
A successful INVITE request establishes a dialog between two user agents
that facilitates a sequence of messages.

Section 15 - Terminating a Session

The BYE request is used to terminate a specific session or attempted session.
A BYE is sent by either user agent to indicate that it wishes to release the call."""

    for line in content.split("\n"):
        pdf.cell(0, 5, line, new_x="LMARGIN", new_y="NEXT")

    output_path = specs_dir / "test_sip_spec.pdf"
    pdf.output(str(output_path))
    print(f"Test spec created: {output_path}")
    return output_path


if __name__ == "__main__":
    create_test_spec()